/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        errorMassage("gates.js");
    }
    public static void errorMassage(String path){
        File file=new File(path);
        int num=0;
        try  {
            Scanner scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
               num++;
                if (scanner.hasNext(";")) {
                    System.out.println(scanner.nextLine());
                }
               else {
                    System.out.println("Line "+num+": Missing semicolon.");
                }
                }
        } catch (FileNotFoundException fileNotFoundException) {
            System.err.println(fileNotFoundException.getMessage());
        }

    }
}
